/* RWCAPP service worker v16 */
const CACHE = 'rwcapp-shell-v16';
const PRECACHE = ['./','./index.html','./styles.css','./app-a.js','./app-b.js','./manifest.webmanifest','./icon.svg'];
const LIVE_HOSTS = ['tgftp.nws.noaa.gov','aviationweather.gov','api.open-meteo.com','marine-api.open-meteo.com','api.allorigins.win','corsproxy.io','r.jina.ai','www.ogimet.com','www.knmidc.org','www.nhc.noaa.gov','api.adsb.lol','opendata.adsb.fi','api.rainviewer.com','tilecache.rainviewer.com','server.arcgisonline.com','basemaps.cartocdn.com','tile.openstreetmap.org','fonts.googleapis.com','fonts.gstatic.com','d.liveatc.net'];
function isLiveRequest(url){return LIVE_HOSTS.some(function(h){return url.hostname===h||url.hostname.endsWith('.'+h);});}
function isHtmlRequest(req,url){if(req.mode==='navigate')return true;if(url.pathname==='/'||url.pathname.endsWith('/')||url.pathname.endsWith('.html'))return true;return (req.headers.get('accept')||'').includes('text/html');}
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){return Promise.allSettled(PRECACHE.map(function(u){return c.add(u);}));}).then(function(){return self.skipWaiting();}));});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.filter(function(k){return k!==CACHE;}).map(function(k){return caches.delete(k);}));}).then(function(){return self.clients.claim();}));});
self.addEventListener('fetch',function(e){var req=e.request;if(req.method!=='GET')return;var url=new URL(req.url);if(isLiveRequest(url))return;var same=url.origin===self.location.origin;var leaflet=url.hostname==='unpkg.com';if(!same&&!leaflet)return;if(same&&isHtmlRequest(req,url)){e.respondWith(networkFirst(req));return;}e.respondWith(cacheFirst(req));});
async function networkFirst(req){var cache=await caches.open(CACHE);try{var fresh=await fetch(req,{cache:'no-store'});if(fresh&&fresh.ok)cache.put(req,fresh.clone());return fresh;}catch(err){var hit=await cache.match(req)||await cache.match('./index.html')||await cache.match('./');if(hit)return hit;throw err;}}
async function cacheFirst(req){var cache=await caches.open(CACHE);var hit=await cache.match(req);if(hit){fetch(req).then(function(res){if(res&&res.ok)cache.put(req,res.clone());}).catch(function(){});return hit;}var res=await fetch(req);if(res&&res.ok)cache.put(req,res.clone());return res;}
